AWSTemplateFormatVersion: 2010-09-09
Description: Deploy infrastructure necessary to alert on GD findings

Parameters:
  EmailAddress:
    Description: Email Address for notifications
    Type: String

Resources:
  AlarmNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: GD-AlarmNotificationTopic
      TopicName: GD-AlarmNotificationTopic
      KmsMasterKeyId: alias/aws/sns
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: email
      
    GuardDutyEventRule:
      Type: AWS::Events::Rule
      Properties: 
        Description: Send GD Findings to Email
        EventPattern: 
          source:
            - aws.guardduty
        Name: GD-Findings
        Targets: 
          - Arn: !Ref AlarmNotificationTopic
            Id: GDAlerts
            InputTransformer:
              InputPathsMap: 
                "severity": "$.detail.severity",
                "Account_ID": "$.detail.accountId",
                "Finding_ID": "$.detail.id",
                "Finding_Type": "$.detail.type",
                "region": "$.region",
                "Finding_description": "$.detail.description" 
              InputTemplate: |
                "AWS <Account_ID> has a severity <severity> GuardDuty finding type <Finding_Type> in the <region> region."
                "Finding Description:"
                "<Finding_description>. "
                "For more details open the GuardDuty console at https://console.aws.amazon.com/guardduty/home?region=<region>#/findings?search=id=<Finding_ID>"
